import { sql, type SQL } from 'drizzle-orm';
import { timestamp, uuid, type AnyPgColumn } from 'drizzle-orm/pg-core';

/** UUID primary key generated by PostgreSQL (`gen_random_uuid()`). */
export const id = () => uuid('id').primaryKey().defaultRandom();

/** TIMESTAMPTZ: stored as an absolute instant (UTC); read back as a JS Date. */
export const timestamptz = (name: string) => timestamp(name, { withTimezone: true, mode: 'date' });

export const createdAt = () => timestamptz('created_at').notNull().defaultNow();

/** Maintained by Drizzle on every `update()`; all writes go through the app. */
export const updatedAt = () =>
  timestamptz('updated_at')
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date());

const SAFE_LITERAL = /^[A-Za-z0-9_.-]+$/;

/**
 * `column IN ('A', 'B', ...)` for CHECK constraints. Values are inlined (DDL
 * cannot take bind parameters), so only simple code-defined literals are
 * accepted.
 */
export function oneOf(column: AnyPgColumn, values: readonly string[]): SQL {
  for (const value of values) {
    if (!SAFE_LITERAL.test(value)) throw new Error(`Unsafe CHECK literal: ${value}`);
  }
  return sql`${column} in (${sql.raw(values.map((value) => `'${value}'`).join(', '))})`;
}

/** `char_length(column) between min and max`. */
export function lengthBetween(column: AnyPgColumn, min: number, max: number): SQL {
  return sql`char_length(${column}) between ${sql.raw(String(min))} and ${sql.raw(String(max))}`;
}

/** UPPER_SNAKE_CASE identifiers such as event types. */
export function upperSnake(column: AnyPgColumn): SQL {
  return sql`${column} ~ '^[A-Z][A-Z0-9_]*$'`;
}
