import { z } from 'zod';

import { ANALYTICS_EVENT_NAMES, type AnalyticsEventName } from '../../db/schema/enums.js';
import { attributionCode, optional } from '../../shared/validation/fields.js';

/**
 * Funnel analytics contracts.
 *
 * Only these events can be reported by the browser. Business outcomes
 * (application_accepted, application_rejected, meeting_booked, ...) are NOT
 * reportable: the funnel reads them from authoritative tables instead.
 */
export const CLIENT_ANALYTICS_EVENTS = [
  'onboarding_view',
  'vsl_start',
  'vsl_25',
  'vsl_50',
  'vsl_75',
  'vsl_complete',
  'application_start',
  'application_submit',
  'scheduling_opened',
] as const satisfies readonly AnalyticsEventName[];
export type ClientAnalyticsEvent = (typeof CLIENT_ANALYTICS_EVENTS)[number];

/** Server-only names, listed for documentation/tests. */
export const SERVER_ONLY_ANALYTICS_EVENTS = ANALYTICS_EVENT_NAMES.filter(
  (name) => !(CLIENT_ANALYTICS_EVENTS as readonly string[]).includes(name),
);

/** Small: one event, a few short fields. */
export const ANALYTICS_BODY_LIMIT_BYTES = 4 * 1024;

const CONTROL_CHARS = /\p{Cc}/u;

/**
 * Path of the page, stored WITHOUT query string or fragment: those can carry
 * emails, tokens (e.g. #token=…), or tracking identifiers.
 */
const pagePath = z
  .string()
  .max(2048)
  .refine((value) => value.startsWith('/') && !value.startsWith('//'), {
    error: 'must be a path starting with "/"',
  })
  .refine((value) => !CONTROL_CHARS.test(value), { error: 'must not contain control characters' })
  .transform((value) => value.split(/[?#]/, 1)[0] ?? '/')
  .pipe(z.string().max(512));

/** Referring page, reduced to its origin (no path, query, or fragment). */
const referrerOrigin = z
  .string()
  .max(2048)
  .pipe(z.url({ protocol: /^https?$/, error: 'must be an http(s) URL' }))
  .transform((value) => new URL(value).origin);

export const analyticsEventRequestSchema = z
  .strictObject({
    event: z.enum(CLIENT_ANALYTICS_EVENTS).describe('Client-reportable funnel event'),
    anonymousSessionId: z
      .string()
      .regex(/^[A-Za-z0-9_-]{8,128}$/, 'must be 8-128 characters of [A-Za-z0-9_-]')
      .describe(
        'Random id generated by the browser per visit (e.g. crypto.randomUUID() kept in sessionStorage). Must not be derived from personal data or a device fingerprint.',
      ),
    ...{
      source: optional(attributionCode).describe('utm_source of the visit, e.g. "instagram"'),
      campaign: optional(attributionCode).describe('utm_campaign of the visit, e.g. "bio"'),
    },
    path: optional(pagePath).describe('Page path; query string and fragment are dropped'),
    referrer: optional(referrerOrigin).describe(
      'document.referrer; only the origin is stored (e.g. https://www.instagram.com)',
    ),
  })
  .meta({ id: 'AnalyticsEvent' });

export type AnalyticsEventRequest = z.output<typeof analyticsEventRequestSchema>;

export const analyticsEventAcceptedSchema = z
  .object({ data: z.object({ status: z.literal('RECORDED') }) })
  .meta({ id: 'AnalyticsEventAccepted' });

// ---- Funnel (admin) ------------------------------------------------------------------

export const MAX_FUNNEL_RANGE_DAYS = 366;
export const DEFAULT_FUNNEL_RANGE_DAYS = 30;

const isoInstant = z.iso
  .datetime({ offset: true, error: 'must be an ISO 8601 date-time with timezone' })
  .transform((value) => new Date(value));

export const funnelQuerySchema = z
  .strictObject({
    from: isoInstant
      .optional()
      .describe(`Inclusive. Default: ${DEFAULT_FUNNEL_RANGE_DAYS} days before \`to\``),
    to: isoInstant.optional().describe('Exclusive. Default: now'),
    source: optional(attributionCode),
    campaign: optional(attributionCode),
  })
  .superRefine((query, ctx) => {
    if (query.from && query.to && query.from >= query.to) {
      ctx.addIssue({ code: 'custom', path: ['to'], message: 'must be after from' });
    }
  });

export type FunnelQuery = z.output<typeof funnelQuerySchema>;

const count = z.number().int().nonnegative();
const ratio = z
  .number()
  .nullable()
  .describe('0–1, rounded to 4 decimals; null when the denominator is 0');

export const funnelResponseSchema = z
  .object({
    data: z.object({
      period: z.object({ from: z.date(), to: z.date() }),
      filters: z.object({ source: z.string().nullable(), campaign: z.string().nullable() }),
      funnel: z
        .object({
          onboardingViews: count.describe('Client: distinct sessions with onboarding_view'),
          vslStarts: count.describe('Client: distinct sessions with vsl_start'),
          vslCompletes: count.describe('Client: distinct sessions with vsl_complete'),
          applicationStarts: count.describe('Client: distinct sessions with application_start'),
          applications: count.describe('Authoritative: applications submitted in the period'),
          accepted: count.describe('Authoritative: of those, accepted (at any time so far)'),
          rejected: count.describe('Authoritative: of those, rejected'),
          meetingsBooked: count.describe(
            'Authoritative: of those, with at least one booked meeting',
          ),
        })
        .meta({ id: 'FunnelCounts' }),
      conversion: z
        .object({
          vslStartRate: ratio.describe('vslStarts / onboardingViews'),
          vslCompletionRate: ratio.describe('vslCompletes / vslStarts'),
          applicationRate: ratio.describe('applications / onboardingViews'),
          applicationCompletionRate: ratio.describe('applications / applicationStarts'),
          acceptanceRate: ratio.describe(
            'accepted / (accepted + rejected): decided applications only',
          ),
          bookingRate: ratio.describe('meetingsBooked / accepted'),
          overallRate: ratio.describe('meetingsBooked / onboardingViews'),
        })
        .meta({ id: 'FunnelConversion' }),
      vslProgress: z.object({
        started: count,
        reached25: count,
        reached50: count,
        reached75: count,
        completed: count,
      }),
      clientReported: z
        .object({
          applicationSubmits: count.describe(
            'Client-reported application_submit sessions (informational; the funnel uses authoritative applications)',
          ),
          schedulingOpened: count,
        })
        .describe('Client events not used as authoritative counts'),
      bySource: z
        .array(
          z.object({
            source: z.string().nullable().describe('null = no source reported'),
            onboardingViews: count,
            vslStarts: count,
            applications: count,
            accepted: count,
            meetingsBooked: count,
            applicationRate: ratio,
          }),
        )
        .describe('Up to 50 sources, busiest first'),
    }),
  })
  .meta({ id: 'FunnelReport' });

export type FunnelReport = z.infer<typeof funnelResponseSchema>['data'];
